version: '2'


networks:
  fin-track:

services:
  postgres.fin-track:
    image: 'postgres:13.4-alpine'
    container_name: postgres.fin-track
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finances
    networks:
      - fin-track
    ports:
      - "5432:5432"
    volumes:
      # - ./postgres/postgres-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql