packages:
- .
resolver:
  compiler: ghc-8.10.7

extra-deps:
- scotty-0.12
- aeson-2.1.0.0
- base-compat-batteries-0.12.2
- blaze-builder-0.4.2.2
- case-insensitive-1.2.1.0
- data-default-class-0.1.2.0
- fail-4.9.0.0
- http-types-0.12.3
- monad-control-1.0.3.1
- nats-1.1.2
- network-3.1.2.7
- regex-compat-0.95.2.1
- transformers-base-0.4.6
- transformers-compat-0.7.2
- wai-3.2.3
- wai-extra-3.1.12.1
- warp-3.3.22
- HUnit-1.6.2.0
- OneTuple-0.3.1
- QuickCheck-2.14.2
- ansi-terminal-0.11.3
- attoparsec-0.14.4
- auto-update-0.1.6
- base-compat-0.12.2
- base-orphans-0.8.7
- base64-bytestring-1.2.1.0
- bsb-http-chunked-0.0.0.4
- call-stack-0.4.0
- cookie-0.4.5
- data-fix-0.3.2
- dlist-1.0
- fast-logger-3.1.1
- generically-0.1
- hashable-1.4.1.0
- http-date-0.0.11
- http2-3.0.3
- indexed-traversable-0.1.2
- iproute-1.7.12
- primitive-0.7.4.0
- regex-base-0.94.0.2
- regex-posix-0.96.0.1
- resourcet-1.2.6
- scientific-0.3.7.0
- semialign-1.2.0.1
- simple-sendfile-0.2.30
- streaming-commons-0.2.2.4
- strict-0.4.0.1
- tagged-0.8.6.1
- text-short-0.1.5
- th-abstraction-0.4.4.0
- these-1.1.1.1
- time-compat-1.9.6.1
- time-manager-0.0.0
- unix-compat-0.6
- unliftio-0.2.22.0
- unordered-containers-0.2.19.1
- uuid-types-1.0.5
- vault-0.3.1.5
- vector-0.13.0.0
- wai-logger-2.4.0
- witherable-0.4.2
- word8-0.1.3
- x509-1.7.7
- appar-0.1.8
- asn1-encoding-0.9.6
- asn1-parse-0.9.5
- asn1-types-0.3.4
- assoc-1.0.2
- async-2.2.4
- byteorder-1.0.4
- cabal-doctest-1.0.9
- colour-2.3.6
- cryptonite-0.30
- easy-file-0.2.2
- hourglass-0.2.12
- indexed-traversable-instances-0.1.1.1
- integer-logarithms-1.0.3.1
- memory-0.17.0
- network-byte-order-0.1.6
- pem-0.2.4
- psqueues-0.2.7.3
- random-1.2.1.1
- semigroupoids-5.3.7
- splitmix-0.1.0.4
- unix-time-0.4.7
- unliftio-core-0.2.0.1
- vector-stream-0.1.0.0
- zlib-0.6.3.0
- basement-0.0.14
- bifunctors-5.5.12
- comonad-5.0.8
- contravariant-1.5.5
- distributive-0.6.2.1
- old-time-1.1.0.3
- StateVar-1.2.2
- old-locale-1.0.0.7
- dates-0.2.3.2
- base-unicode-symbols-0.2.4.2
- syb-0.7.2.1
- postgresql-simple-0.6.4
- Only-0.1
- bytestring-builder-0.10.8.2.0
- postgresql-libpq-0.9.4.3